# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import plotly.graph_objects as go
# import scipy.stats as stats
# # ==========================================
# # 1. PAGE CONFIGURATION
# # ==========================================
# st.set_page_config(
#     page_title="India Critical Mineral Monitor",
#     page_icon="🇮🇳",
#     layout="wide"
# )

# # Title and Header
# st.title("🇮🇳 National Critical Mineral Security Dashboard")
# st.markdown("### Strategic Analysis of Copper, Lithium & Graphite")
# st.markdown("---")

# # ==========================================
# # 2. LOAD DATA
# # ==========================================
# @st.cache_data
# def load_data():
#     # Load Historical Data
#     df = pd.read_csv('all_minerals_merged.csv')
    
#     # Load Forecast Data (if available)
#     try:
#         forecast_df = pd.read_csv('final_forecast_values.csv')
#         # Convert forecast date to datetime
#         forecast_df['Date'] = pd.to_datetime(forecast_df['Date'])
#     except:
#         forecast_df = pd.DataFrame()
        
#     return df, forecast_df

# df, forecast_df = load_data()

# # ==========================================
# # 3. SIDEBAR CONTROLS
# # ==========================================
# st.sidebar.header("🔍 Analysis Filters")
# selected_mineral = st.sidebar.selectbox(
#     "Select Mineral:",
#     options=df['Mineral'].unique()
# )

# # Filter Data based on selection
# mineral_data = df[df['Mineral'] == selected_mineral]
# mineral_forecast = forecast_df[forecast_df['Mineral'] == selected_mineral]

# # ==========================================
# # 4. KEY PERFORMANCE INDICATORS (KPIs)
# # ==========================================
# # Calculate metrics for the latest available year
# latest_year = mineral_data['Year'].max()
# latest_data = mineral_data[mineral_data['Year'] == latest_year]

# total_import_val = latest_data['Value_USD'].sum()
# top_partner = latest_data.loc[latest_data['Value_USD'].idxmax()]['Country']
# top_partner_share = (latest_data['Value_USD'].max() / total_import_val) * 100

# col1, col2, col3 = st.columns(3)
# with col1:
#     st.metric(label=f"Total Imports ({latest_year})", value=f"${total_import_val/1_000_000:.2f} M")
# with col2:
#     st.metric(label="Top Supplier", value=top_partner)
# with col3:
#     st.metric(label="Dependency Risk", value=f"{top_partner_share:.1f}%", 
#               delta="High" if top_partner_share > 50 else "Moderate", delta_color="inverse")

# # ==========================================
# # 5. DASHBOARD TABS
# # ==========================================
# tab1, tab2, tab3 = st.tabs(["🌍 Supply Chain Map", "📈 AI Forecast", "📊 Trade Analysis"])

# with tab1:
#     st.subheader(f"Global Supply Network: {selected_mineral}")
    
#     # World Map Visualization
#     fig_map = px.choropleth(
#         latest_data,
#         locations="Country",
#         locationmode="country names",
#         color="Value_USD",
#         hover_name="Country",
#         color_continuous_scale="Reds",
#         title=f"Import Sources for {selected_mineral} ({latest_year})"
#     )
#     st.plotly_chart(fig_map, use_container_width=True)
    
#     # Data Table
#     st.dataframe(latest_data[['Country', 'Value_USD', 'Volume']].sort_values('Value_USD', ascending=False))

# with tab2:
#     st.subheader("🤖 AI-Driven Price/Volume Forecast (Next 12 Months)")
    
#     if not mineral_forecast.empty:
#         # Combine History (Annual) and Forecast (Monthly) for plotting
#         # Create a simple line chart
        
#         fig_forecast = go.Figure()
        
#         # Plot Forecast
#         fig_forecast.add_trace(go.Scatter(
#             x=mineral_forecast['Date'],
#             y=mineral_forecast['Forecast_Value'],
#             mode='lines+markers',
#             name='AI Forecast',
#             line=dict(color='red', dash='dot')
#         ))
        
#         fig_forecast.update_layout(
#             title="Predicted Trend (Holt-Winters Model)",
#             xaxis_title="Timeline",
#             yaxis_title="projected Value (USD)"
#         )
        
#         st.plotly_chart(fig_forecast, use_container_width=True)
        
#         st.info("💡 **Insight:** The red dotted line represents the machine learning prediction based on historical seasonality and growth trends.")
#     else:
#         st.warning("No forecast data available. Run the forecast engine first.")

# with tab3:
#     st.subheader("📊 Statistical & Economic Analysis")
    
#     # Load detailed data
#     monthly_df = pd.read_csv('monthly_expanded_data.csv') # Generated by forecast engine
#     metrics_df = pd.read_csv('model_metrics.csv')
    
#     col_a, col_b = st.columns(2)
    
#     with col_a:
#         st.markdown("#### 1. Price Variation Analysis")
#         # Plot Unit Price (Value / Volume)
#         # This answers: "Analyze price variations"
#         mineral_monthly = monthly_df[monthly_df['Mineral'] == selected_mineral]
        
#         fig_price = px.line(
#             mineral_monthly, 
#             x='Date', 
#             y='Unit_Price', 
#             title=f"Global Unit Price Trend ($/Unit) - {selected_mineral}",
#             color_discrete_sequence=['green']
#         )
#         st.plotly_chart(fig_price, use_container_width=True)
#         st.caption("Rise in Unit Price indicates global supply tightening.")

#     with col_b:
#         st.markdown("#### 2. Model Performance (Validation)")
#         # Show the accuracy of our Forecast
#         # This answers: "Validate model performance (MAPE, RMSE)"
#         m_metric = metrics_df[metrics_df['Mineral'] == selected_mineral]
#         if not m_metric.empty:
#             st.dataframe(m_metric, hide_index=True)
#             acc_score = 100 - m_metric['MAPE (%)'].values[0]
#             st.progress(int(acc_score))
#             st.write(f"Model Confidence: **{acc_score:.2f}%**")
#         else:
#             st.warning("No metrics available.")

#     st.markdown("---")
#     st.markdown("#### 3. ANOVA Analysis (Structural Change Test)")
    
#     # ANOVA Implementation
#     # Objective: Compare Trade Volumes Pre-2021 vs Post-2021
#     monthly_df['Date'] = pd.to_datetime(monthly_df['Date'])
#     monthly_df['Year'] = monthly_df['Date'].dt.year
    
#     group_pre = monthly_df[(monthly_df['Mineral'] == selected_mineral) & (monthly_df['Year'] <= 2021)]['Value_USD']
#     group_post = monthly_df[(monthly_df['Mineral'] == selected_mineral) & (monthly_df['Year'] > 2021)]['Value_USD']
    
#     if len(group_pre) > 0 and len(group_post) > 0:
#         f_stat, p_value = stats.f_oneway(group_pre, group_post)
        
#         c1, c2, c3 = st.columns(3)
#         c1.metric("F-Statistic", f"{f_stat:.2f}")
#         c2.metric("P-Value", f"{p_value:.4f}")
        
#         # Interpretation
#         if p_value < 0.05:
#             c3.success("Result: Significant Structural Change")
#             st.info(f"✅ The P-Value ({p_value:.4f}) is < 0.05. This statistically proves that {selected_mineral} trade dynamics have fundamentally changed post-2021 (likely due to EV Policy/COVID).")
#         else:
#             c3.warning("Result: No Significant Change")
#             st.info("The trade patterns have remained statistically stable.")
#     else:
#         st.error("Insufficient data for ANOVA test.")




import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import scipy.stats as stats # Required for ANOVA

# ==========================================
# 1. PAGE CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="India Critical Mineral Monitor",
    page_icon="🇮🇳",
    layout="wide"
)

# Title and Header
st.title("🇮🇳 National Critical Mineral Security Dashboard")
st.markdown("### Strategic Analysis: Copper, Lithium & Graphite")
st.markdown("---")

# ==========================================
# 2. LOAD DATA
# ==========================================
@st.cache_data
def load_data():
    # Load Historical Data
    try:
        df = pd.read_csv('all_minerals_merged.csv')
    except:
        st.error("Error: 'all_minerals_merged.csv' not found. Run forecast_engine.py first.")
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

    # Load Forecast Data (3-Year Horizon)
    try:
        forecast_df = pd.read_csv('final_forecast_values.csv')
        forecast_df['Date'] = pd.to_datetime(forecast_df['Date'])
    except:
        forecast_df = pd.DataFrame()

    # Load Monthly Expanded Data (For Price/ANOVA)
    try:
        monthly_df = pd.read_csv('monthly_expanded_data.csv')
        monthly_df['Date'] = pd.to_datetime(monthly_df['Date'])
    except:
        monthly_df = pd.DataFrame()

    # Load Metrics
    try:
        metrics_df = pd.read_csv('model_metrics.csv')
    except:
        metrics_df = pd.DataFrame()
        
    return df, forecast_df, monthly_df, metrics_df

df, forecast_df, monthly_df, metrics_df = load_data()

if df.empty:
    st.stop()

# ==========================================
# 3. SIDEBAR CONTROLS
# ==========================================
st.sidebar.header("🔍 Analysis Filters")
selected_mineral = st.sidebar.selectbox(
    "Select Mineral:",
    options=df['Mineral'].unique()
)

# Filter Data based on selection
mineral_data = df[df['Mineral'] == selected_mineral]
mineral_forecast = forecast_df[forecast_df['Mineral'] == selected_mineral]
mineral_monthly = monthly_df[monthly_df['Mineral'] == selected_mineral]
mineral_metrics = metrics_df[metrics_df['Mineral'] == selected_mineral]

# ==========================================
# 4. KEY PERFORMANCE INDICATORS (KPIs)
# ==========================================
latest_year = mineral_data['Year'].max()
latest_data = mineral_data[mineral_data['Year'] == latest_year]

total_import_val = latest_data['Value_USD'].sum()
top_partner = latest_data.loc[latest_data['Value_USD'].idxmax()]['Country'] if not latest_data.empty else "N/A"
top_partner_share = (latest_data['Value_USD'].max() / total_import_val) * 100 if total_import_val > 0 else 0

col1, col2, col3 = st.columns(3)
with col1:
    st.metric(label=f"Total Imports ({latest_year})", value=f"${total_import_val/1_000_000:.2f} M")
with col2:
    st.metric(label="Top Supplier", value=top_partner)
with col3:
    st.metric(label="Dependency Risk", value=f"{top_partner_share:.1f}%", 
              delta="Critical" if top_partner_share > 50 else "Moderate", delta_color="inverse")

# ==========================================
# 5. DASHBOARD TABS
# ==========================================
tab1, tab2, tab3 = st.tabs(["🌍 Supply Chain Map", "📈 AI Forecast (3 Years)", "📊 Strategic Analytics"])

# --- TAB 1: MAP ---
with tab1:
    st.subheader(f"Global Supply Network: {selected_mineral}")
    
    col_map, col_table = st.columns([2, 1])
    
    with col_map:
        fig_map = px.choropleth(
            latest_data,
            locations="Country",
            locationmode="country names",
            color="Value_USD",
            hover_name="Country",
            color_continuous_scale="Reds",
            title=f"Import Sources ({latest_year})"
        )
        st.plotly_chart(fig_map, use_container_width=True)
    
    with col_table:
        st.write("#### Key Trading Partners")
        st.dataframe(
            latest_data[['Country', 'Value_USD', 'Volume']].sort_values('Value_USD', ascending=False),
            hide_index=True
        )

# --- TAB 2: ARIMA FORECAST ---
with tab2:
    st.subheader(f"Predictive Modeling: {selected_mineral}")
    
    if not mineral_forecast.empty:
        fig_forecast = go.Figure()
        
        # Plot Historical Context (Last 5 Years) from Monthly Data
        fig_forecast.add_trace(go.Scatter(
            x=mineral_monthly['Date'],
            y=mineral_monthly['Value_USD'],
            mode='lines',
            name='Historical (Actual)',
            line=dict(color='blue')
        ))
        
        # Plot ARIMA Forecast (Next 3 Years)
        fig_forecast.add_trace(go.Scatter(
            x=mineral_forecast['Date'],
            y=mineral_forecast['Forecast_Value'],
            mode='lines',
            name='ARIMA Forecast (Projected)',
            line=dict(color='red', dash='dash')
        ))
        
        fig_forecast.update_layout(
            title="Medium-Term Trade Outlook (36 Months)",
            xaxis_title="Timeline",
            yaxis_title="Import Value (USD)",
            legend=dict(orientation="h", y=1.1)
        )
        
        st.plotly_chart(fig_forecast, use_container_width=True)
        
        # Metrics Display
        st.markdown("#### Model Validation Metrics")
        if not mineral_metrics.empty:
            m_col1, m_col2, m_col3, m_col4 = st.columns(4)
            m_col1.metric("Model Used", mineral_metrics['Model'].values[0])
            m_col2.metric("MAPE (Error %)", f"{mineral_metrics['MAPE (%)'].values[0]}%")
            m_col3.metric("RMSE", f"{mineral_metrics['RMSE'].values[0]}")
            m_col4.metric("Forecast Horizon", "3 Years")
            
            st.info(f"💡 **Technical Insight:** An ARIMA {mineral_metrics['Model'].values[0].replace('ARIMA', '')} model was trained. The MAPE of {mineral_metrics['MAPE (%)'].values[0]}% indicates high reliability.")
    else:
        st.warning("No forecast data available.")

# --- TAB 3: ANALYTICS (ANOVA & PRICE) ---
with tab3:
    st.subheader("Statistical & Economic Indicators")
    
    col_a, col_b = st.columns(2)
    
    # 1. Price Variation
    with col_a:
        st.markdown("#### 📉 Global Price Variation")
        if not mineral_monthly.empty:
            fig_price = px.line(
                mineral_monthly, 
                x='Date', 
                y='Unit_Price', 
                title=f"Unit Price Trend ($/Unit)",
                color_discrete_sequence=['green']
            )
            st.plotly_chart(fig_price, use_container_width=True)
            st.caption("Tracking 'Unit Price' helps identify inflation independent of volume.")
    
    # 2. ANOVA Test
    with col_b:
        st.markdown("#### 🧪 Structural Change Test (ANOVA)")
        st.write("Comparing Pre-2021 vs. Post-2021 trade volumes to detect policy impact.")
        
        if not mineral_monthly.empty:
            # Prepare Groups
            monthly_df['Year_Num'] = pd.to_datetime(monthly_df['Date']).dt.year
            group_pre = monthly_df[(monthly_df['Mineral'] == selected_mineral) & (monthly_df['Year_Num'] <= 2021)]['Value_USD']
            group_post = monthly_df[(monthly_df['Mineral'] == selected_mineral) & (monthly_df['Year_Num'] > 2021)]['Value_USD']
            
            if len(group_pre) > 5 and len(group_post) > 5:
                f_stat, p_value = stats.f_oneway(group_pre, group_post)
                
                st.metric("P-Value", f"{p_value:.5f}")
                
                if p_value < 0.05:
                    st.success("**Significant Change Detected**")
                    st.write("The trade dynamics have structurally shifted post-COVID/PLI schemes.")
                else:
                    st.warning("**No Significant Change**")
                    st.write("Trade volumes have remained statistically consistent.")
            else:
                st.info("Insufficient data points for robust ANOVA.")

    # 3. Trade Balance (Visual)
    st.markdown("---")
    st.markdown("#### ⚖️ Historical Trend Analysis")
    annual_trend = df[df['Mineral'] == selected_mineral].groupby('Year')['Value_USD'].sum().reset_index()
    fig_bar = px.bar(
        annual_trend,
        x='Year',
        y='Value_USD',
        title="Annual Import Bill Evolution",
        text_auto='.2s'
    )
    st.plotly_chart(fig_bar, use_container_width=True)